const lowerCaseEN = {
    '`': {"key": "`", "keyCode": 192, "code": "Backquote"},
    '1': {"key": "1", "keyCode": 49, "code": "Digit1"},
    '2': {"key": "2", "keyCode": 50, "code": "Digit2"},
    '3': {"key": "3", "keyCode": 51, "code": "Digit3"},
    '4': {"key": "4", "keyCode": 52, "code": "Digit4"},
    '5': {"key": "5", "keyCode": 53, "code": "Digit5"},
    '6': {"key": "6", "keyCode": 54, "code": "Digit6"},
    '7': {"key": "7", "keyCode": 55, "code": "Digit7"},
    '8': {"key": "8", "keyCode": 56, "code": "Digit8"},         
    '9': {"key": "9", "keyCode": 57, "code": "Digit9"},
    '0': {"key": "0", "keyCode": 48, "code": "Digit0"},
    '-': {"key": "-", "keyCode": 189, "code": "Minus"},
    '=': {"key": "=", "keyCode": 187, "code": "Equal"},
    'Backspace': {"key": "Backspace", "keyCode": 8, "code": "Backspace"},

    'Tab': {"key": "Tab", "keyCode": 9, "code": "Tab"},
    'q': {"key": "q", "keyCode": 81, "code": "KeyQ"},
    'w': {"key": "w", "keyCode": 87, "code": "KeyW"},
    'e': {"key": "e", "keyCode": 69, "code": "KeyE"},
    'r': {"key": "r", "keyCode": 82, "code": "KeyR"},
    't': {"key": "t", "keyCode": 84, "code": "KeyT"},
    'y': {"key": "y", "keyCode": 89, "code": "KeyY"},
    'u': {"key": "u", "keyCode": 85, "code": "KeyU"},
    'i': {"key": "i", "keyCode": 73, "code": "KeyI"},
    'o': {"key": "o", "keyCode": 79, "code": "KeyO"},
    'p': {"key": "p", "keyCode": 80, "code": "KeyP"},
    '[': {"key": "[", "keyCode": 219, "code": "BracketLeft"},
    ']': {"key": "]", "keyCode": 221, "code": "BracketRight"},
    '\\': {"key": "\\", "keyCode": 220, "code": "Backslash"},
    'Del': {"key": "Del", "keyCode": 46, "code": "Delete"},

    'CapsLock': {"key": "Caps Lock", "keyCode": 20, "code": "CapsLock"},
    'a': {"key": "a", "keyCode": 65, "code": "KeyA"},
    's': {"key": "s", "keyCode": 83, "code": "KeyS"},
    'd': {"key": "d", "keyCode": 68, "code": "KeyD"},
    'f': {"key": "f", "keyCode": 70, "code": "KeyF"},
    'g': {"key": "g", "keyCode": 71, "code": "KeyG"},
    'h': {"key": "h", "keyCode": 72, "code": "KeyH"},
    'j': {"key": "j", "keyCode": 74, "code": "KeyJ"},
    'k': {"key": "k", "keyCode": 75, "code": "KeyK"},
    'l': {"key": "l", "keyCode": 76, "code": "KeyL"},
    ';': {"key": ";", "keyCode": 186, "code": "Semicolon"},
    '\'': {"key": "\'", "keyCode": 222, "code": "Quote"},
    'Enter': {"key": "Enter", "keyCode": 13, "code": "Enter"},

    'ShiftLeft': {"key": "Shift", "keyCode": 16, "code": "ShiftLeft"},
    'z': {"key": "z", "keyCode": 90, "code": "KeyZ"},
    'x': {"key": "x", "keyCode": 88, "code": "KeyX"},
    'c': {"key": "c", "keyCode": 67, "code": "KeyC"},
    'v': {"key": "v", "keyCode": 86, "code": "KeyV"},
    'b': {"key": "b", "keyCode": 66, "code": "KeyB"},
    'n': {"key": "n", "keyCode": 78, "code": "KeyN"},
    'm': {"key": "m", "keyCode": 77, "code": "KeyM"},
    ',': {"key": ",", "keyCode": 188, "code": "Comaa"},
    '.': {"key": ".", "keyCode": 190, "code": "Period"},
    '/': {"key": "/", "keyCode": 191, "code": "Slash"},
    'ArrowUp': {"key": "▲", "keyCode": 38, "code": "ArrowUp"},
    'ShiftRight': {"key": "Shift", "keyCode": 16, "code": "ShiftRight"},

    'ControlLeft': {"key": "Ctrl", "keyCode": 17, "code": "ControlLeft"},
    'Win': {"key": "Win", "keyCode": 91, "code": "MetaLeft"},
    'AltLeft': {"key": "Alt", "keyCode": 18, "code": "AltLeft"},
    'Space': { "key": "&nbsp;", "keyCode": 32, "code": "Space"},
    'AltRight': {"key": "Alt", "keyCode": 18, "code": "AltRight"},
    'ArrowLeft': {"key": "◀", "keyCode": 37, "code": "ArrowLeft"},
    'ArrowDown': {"key": "▼", "keyCode": 40, "code": "ArrowDown"},
    'ArrowRight': {"key": "▶", "keyCode": 39, "code": "ArrowRight"},
    'ControlRight': {"key": "Ctrl", "keyCode": 17, "code": "ControlRight"},
}

export default lowerCaseEN;